export const ACTION_OFFER_MAKE = 'ACTION_OFFER_MAKE'
export const ACTION_OFFER_CANCEL = 'ACTION_OFFER_CANCEL'
export const ACTION_OFFER_ACCEPT = 'ACTION_OFFER_ACCEPT'

export const ACTION_FIXED_SELL = 'ACTION_FIXED_SELL'
export const ACTION_FIXED_BUY = 'ACTION_FIXED_BUY'
export const ACTION_FIXED_CANCEL = 'ACTION_FIXED_CANCEL'

export const ACTION_AUCTION_START = 'ACTION_AUCTION_START'
export const ACTION_AUCTION_FINISH = 'ACTION_AUCTION_FINISH'
export const ACTION_AUCTION_BID = 'ACTION_AUCTION_BID'
export const ACTION_AUCTION_BUYOUT = 'ACTION_AUCTION_BUYOUT'
export const ACTION_AUCTION_CANCEL = 'ACTION_AUCTION_CANCEL'

export const ACTION_TOKEN_BURN = 'ACTION_TOKEN_BURN'
export const ACTION_TOKEN_TRNSFER = 'ACTION_TOKEN_TRNSFER'

export const ACTION_SUCCESS = 'ACTION_SUCCESS'
export const ACTION_FAIL = 'ACTION_FAIL'
