export const START_LOADER = 'START_LOADER'
export const FINISH_LOADER = 'FINISH_LOADER'

export const THEME = 'THEME'
export const CONFIG_URLS = 'CONFIG_URLS'
export const MARKET_ALL_NFT = 'MARKET_ALL_NFT'
export const MARKET_DEL_NFT = 'MARKET_DEL_NFT'
export const MARKET_ITEM_OFFERS = 'MARKET_ITEM_OFFERS'
export const MARKET_ITEM_BIDS = 'MARKET_ITEM_BIDS'

export const MARKET_COINS = 'MARKET_COINS'

export const MARKET_BUSY_NFT = 'MARKET_BUSY_NFT'
