version: '3'
services:
  nuxt:
    build:
      context: .
    container_name: om-demo-ibc1
    restart: unless-stopped
    ports:
      - 3000:3000
    volumes:
      - nft-db:/app/db
      - nft-img:/app/static/images/output
    environment:
      - NODE_ENV=development
      - GQL_URL=http://graphql_ibc1:8080/v1/graphql
      - REST_URL=http://marketplace_api_ibc1:1317
      - REST_URL_DST=http://marketplace_api_ibc0:1317
      - VIRTUAL_PORT=3000
      - VIRTUAL_HOST=demo-ibc1.openmarket.one
      - LETSENCRYPT_HOST=demo-ibc1.openmarket.one
#      - DEBUG="true"
    networks:
      - dwh-tier

networks:
  dwh-tier:
    external:
      name: dwh-network

volumes:
  nft-db:
  nft-img:


