version: '3'
services:
  nuxt:
    build:
      context: .
    restart: unless-stopped
    ports:
      - 3000:3000
    environment:
      - NODE_ENV=production
      - GQL_URL=http://graphql:8080/v1/graphql
      - REST_URL=http://merketplace:1317

  nginx:
    image: nginx:1-alpine
    restart: unless-stopped
    ports:
      - "80:80"
    volumes:
      - ./nginx:/etc/nginx/conf.d
    depends_on:
      - nuxt
