version: '3'
services:
  nuxt:
    build:
      context: .
    container_name: openmarket-demo
    restart: unless-stopped
    ports:
      - 3000:3000
    volumes:
      - nft-db:/app/db
      - nft-img:/app/static/images/output
    environment:
      - NODE_ENV=development
      - GQL_URL=http://dwh_graphql:8080/v1/graphql
#      - GQL_URL=http://demo.openmarket.one:8080/v1/graphql
      - REST_URL=http://dwh_marketplace_api:1317
#      - REST_URL=http://demo.openmarket.one:1317
      - VIRTUAL_PORT=3000
      - VIRTUAL_HOST=demo.openmarket.one
      - LETSENCRYPT_HOST=demo.openmarket.one
      - DEBUG="true"
    networks:
      - dwh-tier

networks:
  dwh-tier:
    external:
      name: dwh-network

volumes:
  nft-db:
  nft-img:


